app/focusboard/urls.py
from django.contrib import admin
from django.urls import path,include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView, # testing purpose
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('user.urls')),
    path('api/tasks/', include('tasks.api_urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'), # testing purpose
]

app/tasks/urls.py
"""
Urls for Tasks App
"""

from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('list_all/', views.ListAllTasksView, name='list_task'),
    path('detail/<int:id>/', views.TaskDetail, name='detail'),
    path('create/', views.CreateTask, name='create'),
    path('edit/<int:id>', views.EditTask, name='edit'),
    path('delete/<int:id>', views.DeleteTask, name='delete'),
]

app/user/urls.py
"""
Url mapping for user authentication handling.
"""

from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    # path('register/', views.regsiterView, name='register'),
]

app/tasks/models.py
"""
Model for Tasks
"""
from django.db import models

PRIORITY = [
    ('L', 'low'),
    ('M', 'medium'),
    ('H', 'high'),
]

class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY,
        default='M',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

app/user/models.py
from django.db import models

# Create your models here.

app/tasks/forms.py
"""
Froms for Task App
"""

from django import forms

from tasks.models import Task

class CreateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description',
            'priority', 'is_completed'
        ]
        help_texts = {'title' : 'Enter a Task to do...'}

app/user/forms.py
"""
Form for user app
"""

from django import forms
from django.contrib.auth import get_user_model


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password', 'password2',  'email']

app/tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Task
from .forms import CreateTaskForm

# just a test function
def add(a, b, **extras):
    return a+b

@login_required
def ListAllTasksView(request):

    print(request.user)

    tasks = Task.objects.all().order_by('-created_at')
    messages.success(request, message="ALL Task Listed..")

    return render(request,
            template_name="list_all_task.html",
            context={'tasks':tasks},
            status=200,
        )

@login_required
def TaskDetail(request, id):

    task = get_object_or_404(Task, id=id)

    return render(request, 'detail_task.html', context={'task':task})

@login_required
def CreateTask(request):

    if request.method == 'POST':
        form = CreateTaskForm(request.POST)

        if form.is_valid():
            # data = form.cleaned_data
            # Task.objects.create(**data)
            form.save()

        messages.success(request, message="Task Created Successfully!")

        return redirect('tasks:list_task')
    else:
        form = CreateTaskForm()

    return render(request, 'addtask.html', context={'form':form})

@login_required
def EditTask(request, id):

    task = get_object_or_404(Task, id=id)

    if request.method == 'POST':
        form = CreateTaskForm(request.POST, instance=task)

        if form.is_valid():
            form.save()

        messages.success(request, "Task Updated successfully..")
        return redirect('tasks:detail', id=id)
    else:
        form = CreateTaskForm(instance=task)

    return render(request, 'edit.html', context={'form':form})

@login_required
def DeleteTask(request, id):

    task = get_object_or_404(Task, id=id)

    if request.method == 'POST':
        title = task.title
        task.delete()

        messages.success(request, f"{title}... Task Delete successfully !")
        return redirect('tasks:list_task')

    return render(request, 'delete.html')

app/user/views.py
"""
User authentication logic views.
"""

from django.shortcuts import render, redirect
from django.contrib import messages

from django.contrib.auth import get_user_model, authenticate, login ,logout

from .forms import RegisterForm


User = get_user_model()


# def regsiterView(request):

#     if request.method == 'POST':
#         form = RegisterForm(request.POST)

#         if form.is_valid():
#             form.save()
#             return redirect('user:login')
#         else:
#             messages.error(request, f"{form.errors}")
#             return redirect('user:register')
#     else:
#         form = RegisterForm()

#     return render(request, 'register.html', {'form':form})


# def loginView(request):

#     form = LoginForm()

#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)

#         if user:
#             login(request, user)
#             messages.success(request, f"{user} Logged In!!")
#             return redirect('tasks:list_task')
#         else:
#             messages.error(request, f"{form.errors}")
#             return redirect('user:login')

    # return render(request, 'login.html', {'form':form})

# def logoutView(request):
#     user = request.user

#     logout(request)
#     messages.success(request, f"{user} Logged Out!!")

#     return redirect('user:login')

app/tasks/templates/addtask.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit"> Add Task </button>
    </form>
    {% endblock %}
</body>
</html>

app/tasks/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h4>Delete Task??</h4>
        <button type="submit">YES</button>
    </form>
</body>
</html>

app/tasks/templates/detail_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <h4>{{ message }}</h4>
        {% endfor %}
    {% endif %}
    <h2>Detail of Task:-</h2>
    <hr>
    <h6>{{ task.title }}</h6>
    <h6>{{ task.description }}</h6>
    <h6>{{ task.get_priority_display }}</h6>
    <h6>{{ task.is_completed }}</h6>
    <h6>{{ task.created_at }}</h6>

    <a href="{% url 'tasks:edit' task.id %}"><h3>Edit</h3></a>
    <a href="{% url 'tasks:delete' task.id %}"><h3>Delete</h3></a>

</body>
</html>

app/tasks/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit"> Edit Task </button>
    </form>
</body>
</html>

app/tasks/templates/list_all_task.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% if messages %}
        {% for message in messages %}
            <h4>{{ message }}</h4>
        {% endfor %}
    {% endif %}
    <h1>List of all Tasks:-</h1>
    {% for task in tasks %}
        <a href="{% url 'tasks:detail' task.id %}"><h4>{{ task }}</h4></a>
    {% endfor %}

    <a href="{% url 'tasks:create' %}"><h2>Create new Task</h2></a>
    {% endblock %}
</body>
</html>

app/user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <h4>Logged in Username:-{{ request.user }}</h4>
    <form method="POST" action="{% url 'user:logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
    {% else %}
        <a href=""><button type="submit">Register</button></a>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

app/user/templates/register.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% if messages %}
        {% for message in messages %}
            <h4>{{ message }}</h4>
        {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Register➕</button>
    </form>

    {% endblock %}

</body>
</html>